version: '3'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ../automator
      dockerfile: ../automator/Dockerfile
    ports:
      - "8080:8080"
